from tools import Table

board = {
    'investigators'     :   [  ],
    'current_player'    :   0,
    'current_phase'     :   1,
    'bookkeeping'       :   1,
    'ancient_one'       :   [ ],
    'doom_track'        :   0,
    'terror_track'      :   0,
    'gates_open'        :   0,
    'gates_sealed'      :   0,
    'clues_to_seal'     :   5,
    'win_cond'          :   [ 0, 6 ],
    'monster_limit'     :   4,
    'outskirts_limit'   :   7,
    'monster_locations' :   [ [],[],[],[],[],[],[],[],[] ]
}

locations = [
    ['name',                            'occupants',    'status'     ],
    ['CURIOSITIE SHOPPE',               [],             [0,0,0,0,0,0]],
    ['NEWSPAPER' ,                      [],             [0,0,0,0,0,0]],
    ['TRAIN STATION',                   [],             [0,0,0,0,0,0]],
    ['ARKHAM ASYLUM',                   [],             [0,0,0,0,0,0]],
    ['BANK OF ARKHAM',                  [],             [0,0,0,0,0,0]],
    ['INDEPENDENCE SQUARE',             [],             [1,1,0,0,0,0]],
    ['HIBB\'S ROADHOUSE',               [],             [1,1,0,0,0,0]],
    ['POLICE STATION',                  [],             [0,0,0,0,0,0]],
    ['JAIL CELL',                       [],             [0,0,0,0,0,0]],
    ['VELMA\'S DINER',                  [],             [0,0,0,0,0,0]],
    ['RIVER DOCKS',                     [],             [0,0,0,0,0,0]],
    ['THE UNNAMABLE',                   [],             [1,1,0,0,0,0]],
    ['UNVISITED ISLE',                  [],             [1,1,0,0,0,0]],
    ['BLACK CAVE',                      [],             [1,1,0,0,0,0]],
    ['GENERAL STORE',                   [],             [0,0,0,0,0,0]],
    ['GRAVEYARD',                       [],             [1,1,0,0,0,0]],
    ['ADMINISTRATION',                  [],             [0,0,0,0,0,0]],
    ['SCIENCE BUILDING',                [],             [1,1,0,0,0,0]],
    ['LIBRARY',                         [],             [1,1,0,0,0,0]],
    ['THE WITCH HOUSE',                 [],             [1,1,0,0,0,0]],
    ['THE SILVER TWILIGHT LODGE',       [],             [1,1,0,0,0,0]],
    ['THE INNER SANCTUM',               [],             [0,0,0,0,0,0]],
    ['ST. MARY\'S HOSPITAL',            [],             [0,0,0,0,0,0]],
    ['WOODS',                           [],             [1,1,0,0,0,0]],
    ['YE OLDE MAGICK SHOPPE',           [],             [0,0,0,0,0,0]],
    ['MA\'S BOARDING HOUSE',            [],             [0,0,0,0,0,0]],
    ['HISTORICAL SOCIETY',              [],             [1,1,0,0,0,0]],
    ['SOUTH CHURCH',                    [],             [0,0,0,0,0,0]],
    ['NORTHSIDE STREETS',               [],             [0,0,0,0,0,0]],
    ['DOWNTOWN STREETS',                [],             [0,0,0,0,0,0]],
    ['EASTTOWN STREETS',                [],             [0,0,0,0,0,0]],
    ['MERCHANT DISTRICT STREETS',       [],             [0,0,0,0,0,0]],
    ['RIVERTOWN STREETS',               [],             [0,0,0,0,0,0]],
    ['MISKATONIC UNIVERSITY STREETS',   [],             [0,0,0,0,0,0]],
    ['FRENCH HILL STREETS',             [],             [0,0,0,0,0,0]],
    ['UPTOWN STREETS',                  [],             [0,0,0,0,0,0]],
    ['SOUTHSIDE STREETS',               [],             [0,0,0,0,0,0]],
    ['OUTSKIRTS',                       [],             [0,0,0,0,0,0]],
    ['R\'LYEH',                         [],             [0,0,0,0,0,0]],
    ['PLATEAU OF LENG',                 [],             [0,0,0,0,0,0]],
    ['THE DREAMLANDS',                  [],             [0,0,0,0,0,0]],
    ['GREAT HALL OF CELEANO',           [],             [0,0,0,0,0,0]],
    ['YUGGOTH',                         [],             [0,0,0,0,0,0]],
    ['CITY OF THE GREAT RACE',          [],             [0,0,0,0,0,0]],
    ['ABYSS',                           [],             [0,0,0,0,0,0]],
    ['ANOTHER DIMENSION',               [],             [0,0,0,0,0,0]]
]

monsters = [
    ['name',                     'rulesets',    'abilities',                'stats'                  ],
    ['Byakhee',                  [ 3, 0, 0 ],   [ 0, 0, 0, 1, 1, 0, 0 ],    [ -2, 1, -1, 1, 0, 1 ]   ],
    ['Chthonian',                [ 4, 0, 0 ],   [ 0, 0, 0, 1, 1, 0, 0 ],    [ 1, 3, -2, 2, -3, 3 ]   ],
    ['Cultist',                  [ 0, 0, 0 ],   [ 0, 0, 0, 1, 1, 0, 0 ],    [ -3, 1, 0, 0, 1, 1 ]    ],
    ['Dark Young',               [ 2, 0, 0 ],   [ 0, 0, 0, 0.5, 1, 1, 0 ],  [ -2, 3, 0, 3, -1, 3 ]   ],
    ['Dhole',                    [ 0, 0, 0 ],   [ 0, 0, 0, 0.5, 0.5, 1, 1], [ -1, 3, -1, 4, -3, 4 ]  ],
    ['Dimensional Shambler',     [ 1, 0, 1 ],   [ 0, 0, 0, 1, 1, 0, 0 ],    [ -3, 1, -2, 1, -2, 0 ]  ],
    ['Elder Thing',              [ 0, 1, 2 ],   [ 0, 0, 0, 1, 1, 0, 0 ],    [ -2, 2, -3, 2, 0, 1 ]   ],
    ['Fire Vampire',             [ 3, 0, 0 ],   [ 1, 0, 0, 0, 1, 0, 0],     [ 0, 1, 0, 0, -2, 2 ]    ],
    ['Flying Polyp',             [ 3, 0, 0 ],   [ 0, 0, 0, 0.5, 1, 1, 1 ],  [ 0, 3, -2, 4, -3, 3 ]   ],
    ['Formless Spawn',           [ 0, 0, 0 ],   [ 0, 0, 0, 0, 1, 0, 0 ],    [ 0, 2, -1, 2, -2, 2 ]   ],
    ['Ghost',                    [ 2, 0, 0 ],   [ 0, 0, 1, 0, 1, 0, 0 ],    [ -3, 1, -2, 2, -2, 2 ]  ],
    ['Ghoul',                    [ 0, 0, 0 ],   [ 1, 0, 0, 1, 1, 0, 0, ],   [ -3, 1, 0, 1, -1, 1 ]   ],
    ['God of the Bloody Tongue', [ 0, 0, 0 ],   [ 0, 1, 0, 1, 1, 0, 1 ],    [ 1, 4, -3, 3, -4, 4 ]   ],
    ['Gug',                      [ 0, 0, 0 ],   [ 0, 0, 0, 1, 1, 0, 1],     [ -2, 3, -1, 2, -2, 4 ]  ],
    ['Haunter of the Dark',      [ 3, 0, 0 ],   [ 0, 1, 0, 1, 1, 0, 0 ],    [ -3, 2, -2, 2, -2, 2 ]  ],
    ['High Priest',              [ 0, 0, 0 ],   [ 0, 0, 0, 1, 0, 0, 0 ],    [ -2, 2, 1, 1, -1, 2 ]   ],
    ['Hound of Tindalos',        [ 5, 0, 0 ],   [ 0, 0, 0, 0, 1, 0, 0 ],    [ -1, 2, -2, 4,  -1, 3 ] ],
    ['Maniac',                   [ 0, 0, 0 ],   [ 0, 0, 0, 1, 1, 0, 0 ],    [ -1, 1, 0, 0, 1, 1 ]    ],
    ['Mi-Go',                    [ 3, 0, 3 ],   [ 0, 0, 0, 1, 1, 0, 0 ],    [ -2, 1, -1, 2, 0, 1 ]   ],
    ['Nightgaunt',               [ 3, 2, 4 ],   [ 0, 0, 0, 1, 1, 0, 0 ],    [ -2, 2, -1, 1, -2, 0 ]  ],
    ['Shoggoth',                 [ 1, 0, 0 ],   [ 0, 0, 0, 0.5, 1, 1, 0 ],  [ -1, 3, -1, 3, -1, 3 ]  ],
    ['Star Spawn',               [ 0, 0, 0 ],   [ 0, 0, 0, 1, 1, 0, 0 ],    [ -1, 3, -3, 2, -3, 3 ]  ],
    ['The Black Man',            [ 0, 0, 5 ],   [ 0, 1, 0, 1, 1, 0, 0 ],    [ -3, 1, 0, 0, 0, 0 ]    ],
    ['The Bloated Woman',        [ 0, 0, 6 ],   [ 0, 0, 0, 1, 1, 0, 0 ],    [ -1, 2, -1, 2, -2, 2 ]  ],
    ['The Dark Pharaoh',         [ 0, 0, 7 ],   [ 0, 0, 0, 1, 1, 0, 0 ],    [ -1, 2, -1, 1, -3, 3 ]  ],
    ['Vampire',                  [ 0, 0, 0 ],   [ 0, 0, 1, 0.5, 1, 0, 0 ],  [ -3, 1, 0, 2, -3, 3 ]   ],
    ['Warlock',                  [ 2, 0, 8 ],   [ 0, 0, 0, 1, 0, 0, 0 ],    [ -3, 2, -1, 1, -3, 1 ]  ],
    ['Witch',                    [ 0, 0, 0 ] ,  [ 0, 0, 0, 1, 0.5, 0, 0 ],  [ -1, 1, 0, 0, -3, 2]    ],
    ['Zombie',                   [ 0, 0, 0 ],   [ 0, 0, 1, 1, 1, 0, 0 ],    [ 1, 1, -1, 1, -1, 2]    ],
]
 
monster_cup = {
    'Byakhee'                   : 3,
    'Chthonian'                 : 2,
    'Cultist'                   : 6,
    'Dark Young'                : 3,
    'Dhole'                     : 1,
    'Dimensional Shambler'      : 2,
    'Elder Thing'               : 2,
    'Fire Vampire'              : 2,
    'Flying Polyp'              : 1, 
    'Formless Spawn'            : 2, 
    'Ghost'                     : 3,
    'Ghoul'                     : 3,
    'God of the Bloody Tongue'  : 0,
    'Gug'                       : 2,
    'Haunter of the Dark'       : 0,
    'High Priest'               : 1,
    'Hound of Tindalos'         : 2,
    'Maniac'                    : 3,
    'Mi-Go'                     : 3,
    'Nightgaunt'                : 2,
    'Shoggoth'                  : 2,
    'Star Spawn'                : 2,
    'The Black Man'             : 0,
    'The Bloated Woman'         : 0,
    'The Dark Pharaoh'          : 0,
    'Vampire'                   : 1, 
    'Warlock'                   : 2,
    'Witch'                     : 2,
    'Zombie'                    : 3
}

investigators = [
    ['name',            'damage',  'horror',  'conditions',             'focus',   'speed',   'fight',   'lore',    'location', 'random_possessions', 'equipped_items', 'exhausted_items', 'possessions'],
    ['Amanda Sharpe',   [5, 0, 0], [5, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [2, 2, 0], [4, 4, 5], [4, 4, 5], [4, 4, 5], [19, 0, 1], [1, 1, 1, 2],         [2, []],          [],                {'money': 1, 'clues': 1, 'gate_trophies': 0, 'monster_trophies': 0, 'weapons': [], 'consumables' : [], 'tomes': [], 'passive_buffs': [], 'active_buffs' : [], 'oddities': [], 'spells': [], 'allies': []}],
    ['"Ashcan" Pete',   [5, 0, 0], [5, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [1, 1, 0], [3, 3, 6], [5, 5, 7], [3, 3, 3], [11, 0, 1], [1, 1, 0, 1],         [2, []],          [],                {'money': 1, 'clues': 3, 'gate_trophies': 0, 'monster_trophies': 0, 'weapons': [], 'consumables' : [], 'tomes': [], 'passive_buffs': [], 'active_buffs' : [], 'oddities': [], 'spells': [], 'allies': ['DUKE']}],
    ['Bob Jenkins',     [6, 0, 0], [4, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [1, 1, 0], [5, 5, 5], [4, 4, 7], [3, 3, 4], [15, 0, 1], [2, 2, 0, 1],         [2, []],          [],                {'money': 9, 'clues': 0, 'gate_trophies': 0, 'monster_trophies': 0, 'weapons': [], 'consumables' : [], 'tomes': [], 'passive_buffs': [], 'active_buffs' : [], 'oddities': [], 'spells': [], 'allies': []}],
    ['Carolyn Fern',    [4, 0, 0], [6, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [2, 2, 0], [3, 3, 3], [4, 4, 5], [5, 5, 7], [4, 0, 1],  [2, 2, 0, 1],         [2, []],          [],                {'money': 7, 'clues': 1, 'gate_trophies': 0, 'monster_trophies': 0, 'weapons': [], 'consumables' : [], 'tomes': [], 'passive_buffs': [], 'active_buffs' : [], 'oddities': [], 'spells': [], 'allies': []}],
    ['Darrell Simmons', [6, 0, 0], [4, 0, 0], [0, 0, 0, 2, 0, 0, 0, 0], [2, 2, 0], [5, 5, 5], [5, 5, 6], [3, 3, 4], [2, 0, 1],  [1, 2, 0, 1],         [2, []],          [],                {'money': 4, 'clues': 1, 'gate_trophies': 0, 'monster_trophies': 0, 'weapons': [], 'consumables' : [], 'tomes': [], 'passive_buffs': [], 'active_buffs' : [], 'oddities': [], 'spells': [], 'allies': []}],
    ['Dexter Drake',    [5, 0, 0], [5, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [2, 2, 0], [5, 5, 6], [4, 4, 4], [5, 5, 5], [25, 0, 1], [1, 1, 2, 1],         [2, []],          [],                {'money': 5, 'clues': 0, 'gate_trophies': 0, 'monster_trophies': 0, 'weapons': [], 'consumables' : [], 'tomes': [], 'passive_buffs': [], 'active_buffs' : [], 'oddities': [], 'spells': ['SHRIVELLING'], 'allies': []}],
    ['Gloria Goldberg', [4, 0, 0], [6, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [2, 2, 0], [4, 4, 4], [3, 3, 5], [4, 4, 6], [10, 0, 1], [2, 0, 2, 1],         [2, []],          [],                {'money': 7, 'clues': 2, 'gate_trophies': 0, 'monster_trophies': 0, 'weapons': [], 'consumables' : [], 'tomes': [], 'passive_buffs': [], 'active_buffs' : [], 'oddities': [], 'spells': [], 'allies': []}],
    ['Harvey Walters',  [3, 0, 0], [7, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [2, 2, 0], [3, 3, 5], [3, 3, 3], [6, 6, 7], [17, 0, 1], [0, 2, 2, 1],         [2, []],          [],                {'money': 5, 'clues': 1, 'gate_trophies': 0, 'monster_trophies': 0, 'weapons': [], 'consumables' : [], 'tomes': [], 'passive_buffs': [], 'active_buffs' : [], 'oddities': [], 'spells': [], 'allies': []}],
    ['Jenny Barnes',    [4, 0, 0], [6, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [1, 1, 0], [3, 3, 4], [4, 4, 6], [4, 4, 6], [3, 0, 1],  [2, 1, 1, 1],         [2, []],          [],                {'money': 10, 'clues': 0, 'gate_trophies': 0, 'monster_trophies': 0, 'weapons': [], 'consumables' : [], 'tomes': [], 'passive_buffs': [], 'active_buffs' : [], 'oddities': [], 'spells': [], 'allies': []}],
    ['Joe Diamond',     [6, 0, 0], [4, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [3, 3, 0], [6, 6, 7], [5, 5, 5], [3, 3, 0], [8, 0, 1],  [2, 0, 0, 1],         [2, []],          [],                {'money': 8, 'clues': 3, 'gate_trophies': 0, 'monster_trophies': 0, 'weapons': ['.45 AUTOMATIC'], 'consumables' : [], 'tomes': [], 'passive_buffs': [], 'active_buffs' : [], 'oddities': [], 'spells': [], 'allies': []}],
    ['Kate Winthrop',   [4, 0, 0], [6, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [1, 1, 0], [4, 4, 6], [4, 4, 4], [5, 5, 6], [18, 0, 1], [1, 1, 2, 1],         [2, []],          [],                {'money': 7, 'clues': 2, 'gate_trophies': 0, 'monster_trophies': 0, 'weapons': [], 'consumables' : [], 'tomes': [], 'passive_buffs': [], 'active_buffs' : [], 'oddities': [], 'spells': [], 'allies': []}],
    ['Mandy Thompson',  [5, 0, 0], [5, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [2, 2, 0], [4, 4, 6], [3, 3, 5], [4, 4, 4], [19, 0, 1], [2, 1, 0, 1],         [2, []],          [],                {'money': 6, 'clues': 4, 'gate_trophies': 0, 'monster_trophies': 0, 'weapons': [], 'consumables' : [], 'tomes': [], 'passive_buffs': [], 'active_buffs' : [], 'oddities': [], 'spells': [], 'allies': []}],
    ['Michael McGlen',  [7, 0, 0], [3, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [1, 1, 0], [5, 5, 6], [6, 6, 7], [3, 3, 3], [26, 0, 1], [0, 1, 0, 1],         [2, []],          [],                {'money': 8, 'clues': 0, 'gate_trophies': 0, 'monster_trophies': 0, 'weapons': ['DYNAMITE', 'TOMMY GUN'], 'consumables' : [], 'tomes': [], 'passive_buffs': [], 'active_buffs' : [], 'oddities': [], 'spells': [], 'allies': []}],
    ['Monterey Jack',   [7, 0, 0], [3, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [2, 2, 0], [4, 4, 4], [5, 5, 5], [4, 4, 6], [1, 0, 1],  [0, 2, 0, 1],         [2, []],          [],                {'money': 7, 'clues': 1, 'gate_trophies': 0, 'monster_trophies': 0, 'weapons': ['BULLWHIP', '.38 REVOLVER'], 'consumables' : [], 'tomes': [], 'passive_buffs': [], 'active_buffs' : [], 'oddities': [], 'spells': [], 'allies': []}],
    ['Sister Mary',     [3, 0, 0], [7, 0, 0], [0, 0, 0, 2, 0, 0, 0, 2], [1, 1, 0], [4, 4, 5], [3, 3, 4], [4, 4, 7], [28, 9, 1], [0, 0, 2, 1],         [2, []],          [],                {'money': 0, 'clues': 0, 'gate_trophies': 0, 'monster_trophies': 0, 'weapons': ['CROSS', 'HOLY WATER'], 'consumables' : [], 'tomes': [], 'passive_buffs': [], 'active_buffs' : [], 'oddities': [], 'spells': [], 'allies': []}],
    ['Vincent Lee',     [5, 0, 0], [5, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [2, 2, 0], [3, 3, 5], [3, 3, 4], [5, 5, 6], [23, 0, 1], [2, 0, 2, 1],         [2, []],          [],                {'money': 9, 'clues': 1, 'gate_trophies': 0, 'monster_trophies': 0, 'weapons': [], 'consumables' : [], 'tomes': [], 'passive_buffs': [], 'active_buffs' : [], 'oddities': [], 'spells': [], 'allies': []}]
]

weapons = Table([
    ['name',                'stats'                 ],
    ['.22 DERRINGER',       [ 0, 2, 0, 0, 0, 3 ]    ],
    ['.38 REVOLVER',        [ 0, 3, 0, 0, 1, 4 ]    ],
    ['.45 AUTOMATIC',       [ 0, 4, 0, 0, 1, 5 ]    ],
    ['AXE',                 [ 0, 2, 0, 0, 1, 3 ]    ],
    ['BULLWHIP',            [ 0, 1, 0, 1, 1, 2 ]    ],
    ['CAVALRY SABRE',       [ 0, 2, 0, 0, 1, 3 ]    ],
    ['DYNAMITE',            [ 0, 8, 0, 0, 1, 4 ]    ],
    ['KNIFE',               [ 0, 1, 0, 0, 1, 2 ]    ],
    ['RIFLE',               [ 0, 5, 0, 0, 1, 6 ]    ],
    ['SHOTGUN',             [ 0, 4, 0, 0, 1, 6 ]    ],
    ['TOMMY GUN',           [ 0, 6, 0, 0, 1, 7 ]    ],
    ['CROSS',               [ 1, 0, 0, 0, 1, 3 ]    ],
    ['ENCHANTED BLADE',     [ 1, 4, 0, 0, 1, 6 ]    ],
    ['ENCHANTED KNIFE',     [ 1, 3, 0, 0, 1, 5 ]    ],
    ['HOLY WATER',          [ 1, 6, 0, 0, 1, 4 ]    ],
    ['POWDER OF IBN-GHAZI', [ 1, 9, 1, 0, 1, 6 ]    ],
    ['SWORD OF GLORY',      [ 1, 6, 0, 0, 1, 8 ]    ],
    ['LAMP OF ALHAZRED',    [ 1, 5, 0, 0, 1, 7 ]    ]
])

weapons_deck = {
    '.22 DERRINGER'         : 2,
    '.38 REVOLVER'          : 2,
    '.45 AUTOMATIC'         : 2,
    'AXE'                   : 2,
    'BULLWHIP'              : 2,
    'CAVALRY SABRE'         : 2,
    'DYNAMITE'              : 2,
    'KNIFE'                 : 2,
    'RIFLE'                 : 2,
    'SHOTGUN'               : 2,
    'TOMMY GUN'             : 2,
    'CROSS'                 : 2,
    'ENCHANTED BLADE'       : 2,
    'ENCHANTED KNIFE'       : 2,
    'HOLY WATER'            : 4,
    'POWDER OF IBN-GHAZI'   : 1,
    'SWORD OF GLORY'        : 1,
    'LAMP OF ALHAZRED'      : 1
}