board = {
    'investigators' :       [ ],
    'current_player' :      [ ],
    'current_phase' :       [ ],
    'bookkeeping' :         [ ],
    'ancient_one' :         [ ],
    'doom_track' :          [ ],
    'terror_track' :        [ ],
    'gates_open' :          [ ],
    'gates_sealed' :        [ ],
    'clues_to_seal' :       [ ],
    'win_cond' :            [ ],
    'monster_limit' :       [ ],
    'outskirts_limit' :     [ ],
    'monster_locations' :   [ ]
}

locations = [
    ['name',                            'occupants',    'status'    ],
    ['CURIOSITIE SHOPPE',               [],             []          ],
    [ 'NEWSPAPER' ,                     [],             []          ],
    ['TRAIN STATION',                   [],             []          ],
    ['ARKHAM ASYLUM',                   [],             []          ],
    ['BANK OF ARKHAM',                  [],             []          ],
    ['INDEPENDENCE SQUARE',             [],             []          ],
    ['HIBB\'S ROADHOUSE',               [],             []          ],
    ['POLICE STATION',                  [],             []          ],
    ['JAIL CELL',                       [],             []          ],
    ['VELMA\'S DINER',                  [],             []          ],
    ['RIVER DOCKS',                     [],             []          ],
    ['THE UNNAMABLE',                   [],             []          ],
    ['UNVISITED ISLE',                  [],             []          ],
    ['BLACK CAVE',                      [],             []          ],
    ['GENERAL STORE',                   [],             []          ],
    ['GRAVEYARD',                       [],             []          ],
    ['ADMINISTRATION',                  [],             []          ],
    ['SCIENCE BUILDING',                [],             []          ],
    ['LIBRARY',                         [],             []          ],
    ['THE WITCH HOUSE',                 [],             []          ],
    ['THE SILVER TWILIGHT LODGE',       [],             []          ],
    ['THE INNER SANCTUM',               [],             []          ],
    ['ST. MARY\'S HOSPITAL',            [],             []          ],
    ['WOODS',                           [],             []          ],
    ['YE OLDE MAGICK SHOPPE',           [],             []          ],
    ['MA\'S BOARDING HOUSE',            [],             []          ],
    ['HISTORICAL SOCIETY',              [],             []          ],
    ['SOUTH CHURCH',                    [],             []          ],
    ['NORTHSIDE STREETS',               [],             []          ],
    ['DOWNTOWN STREETS',                [],             []          ],
    ['EASTTOWN STREETS',                [],             []          ],
    ['MERCHANT DISTRICT STREETS',       [],             []          ],
    ['RIVERTOWN STREETS',               [],             []          ],
    ['MISKATONIC UNIVERSITY STREETS',   [],             []          ],
    ['FRENCH HILL STREETS',             [],             []          ],
    ['UPTOWN STREETS',                  [],             []          ],
    ['SOUTHSIDE STREETS',               [],             []          ],
    ['OUTSKIRTS',                       [],             []          ],
    ['R\'LYEH',                         [],             []          ],
    ['PLATEAU OF LENG',                 [],             []          ],
    ['THE DREAMLANDS',                  [],             []          ],
    ['GREAT HALL OF CELEANO',           [],             []          ],
    ['YUGGOTH',                         [],             []          ],
    ['CITY OF THE GREAT RACE',          [],             []          ],
    ['ABYSS',                           [],             []          ],
    ['ANOTHER DIMENSION',               [],             []          ]
]

monsters = [
    ['name',                     'rulesets',    'abilities',  'stats'  ],
    ['Byakhee',                  [  ],          [  ],         [  ]     ],
    ['Cultist',                  [  ],          [  ],         [  ]     ],
    ['Dark Young',               [  ],          [  ],         [  ]     ],
    ['Chthonian',                [  ],          [  ],         [  ]     ],
    ['Dhole',                    [  ],          [  ],         [  ]     ],
    ['Dimensional Shambler',     [  ],          [  ],         [  ]     ],
    ['Elder Thing',              [  ],          [  ],         [  ]     ],
    ['Fire Vampire',             [  ],          [  ],         [  ]     ],
    ['Flying Polyp',             [  ],          [  ],         [  ]     ],
    ['Formless Spawn',           [  ],          [  ],         [  ]     ],
    ['Ghost',                    [  ],          [  ],         [  ]     ],
    ['Ghoul',                    [  ],          [  ],         [  ]     ],
    ['God of the Bloody Tongue', [  ],          [  ],         [  ]     ],
    ['Gug',                      [  ],          [  ],         [  ]     ],
    ['Haunter of the Dark',      [  ],          [  ],         [  ]     ],
    ['High Priest',              [  ],          [  ],         [  ]     ],
    ['Hound of Tindalos',        [  ],          [  ],         [  ]     ],
    ['Maniac',                   [  ],          [  ],         [  ]     ],
    ['Mi-Go',                    [  ],          [  ],         [  ]     ],
    ['Nightgaunt',               [  ],          [  ],         [  ]     ],
    ['Shoggoth',                 [  ],          [  ],         [  ]     ],
    ['Star Spawn',               [  ],          [  ],         [  ]     ],
    ['The Black Man',            [  ],          [  ],         [  ]     ],
    ['The Bloated Woman',        [  ],          [  ],         [  ]     ],
    ['The Dark Pharaoh',         [  ],          [  ],         [  ]     ],
    ['Vampire',                  [  ],          [  ],         [  ]     ],
    ['Warlock',                  [  ],          [  ],         [  ]     ],
    ['Witch',                    [  ],          [  ],         [  ]     ],
    ['Zombie',                   [  ],          [  ],         [  ]     ],
]

monster_cup = [ ]

investigators = [
    ['name',            'damage',   'horror',   'conditions',   'focus',   'speed',   'fight',   'lore',    'location', 'random_possessions',    'equipped_items',   'exhausted_items', 'possessions'   ],
    ['Amanda Sharpe',   [],         [],         [],             [],        [],       [],         [],        [],         [],                      [],                 [],                []              ],
    ['"Ashcan" Pete',   [],         [],         [],             [],        [],       [],         [],        [],         [],                      [],                 [],                []              ],
    ['Bob Jenkins',     [],         [],         [],             [],        [],       [],         [],        [],         [],                      [],                 [],                []              ],
    ['Carolyn Fern',    [],         [],         [],             [],        [],       [],         [],        [],         [],                      [],                 [],                []              ],
    ['Darrell Simmons', [],         [],         [],             [],        [],       [],         [],        [],         [],                      [],                 [],                []              ],
    ['Dexter Drake',    [],         [],         [],             [],        [],       [],         [],        [],         [],                      [],                 [],                []              ],
    ['Gloria Goldberg', [],         [],         [],             [],        [],       [],         [],        [],         [],                      [],                 [],                []              ],
    ['Harvey Walters',  [],         [],         [],             [],        [],       [],         [],        [],         [],                      [],                 [],                []              ],
    ['Jenny Barnes',    [],         [],         [],             [],        [],       [],         [],        [],         [],                      [],                 [],                []              ],
    ['Joe Diamond',     [],         [],         [],             [],        [],       [],         [],        [],         [],                      [],                 [],                []              ],
    ['Kate Winthrop',   [],         [],         [],             [],        [],       [],         [],        [],         [],                      [],                 [],                []              ],
    ['Mandy Thompson',  [],         [],         [],             [],        [],       [],         [],        [],         [],                      [],                 [],                []              ],
    ['Michael McGlen',  [],         [],         [],             [],        [],       [],         [],        [],         [],                      [],                 [],                []              ],
    ['Monterey Jack',   [],         [],         [],             [],        [],       [],         [],        [],         [],                      [],                 [],                []              ],
    ['Sister Mary',     [],         [],         [],             [],        [],       [],         [],        [],         [],                      [],                 [],                []              ],
    ['Vincent Lee',     [],         [],         [],             [],        [],       [],         [],        [],         [],                      [],                 [],                []              ]
]

weapons = [
    ['name',                'stats'                                 ],
    ['.22 DERRINGER',       [  ]                                    ],
    ['.38 REVOLVER',        [  ]                                    ],
    ['.45 AUTOMATIC',       [  ]                                    ],
    ['AXE',                 [  ]                                    ],
    ['BULLWHIP',            [  ]                                    ],
    ['CAVALRY SABRE',       [  ]                                    ],
    ['DYNAMITE',            [  ]                                    ],
    ['KNIFE',               [  ]                                    ],
    ['RIFLE',               [  ]                                    ],
    ['SHOTGUN',             [  ]                                    ],
    ['TOMMY GUN',           [  ]                                    ],
    ['CROSS',               [  ]                                    ],
    ['ENCHANTED BLADE',     [  ]                                    ],
    ['ENCHANTED KNIFE',     [  ]                                    ],
    ['HOLY WATER',          [  ]                                    ],
    ['POWDER OF IBN-GHAZI', [  ]                                    ],
    ['SWORD OF GLORY',      [  ]                                    ],
    ['LAMP OF ALHAZRED',    [  ]                                    ]
]

weapons_deck = [ ]
